SmartElectronicsApi.Mvc/ViewModels/Color/ColorListItemVM.cs
namespace SmartElectronicsApi.Mvc.ViewModels.Color
{
    public class ColorListItemVM
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
    }
}

SmartElectronicsApi.Mvc/ViewModels/Color/ColorVM.cs
namespace SmartElectronicsApi.Mvc.ViewModels.Color
{
    public class ColorVM
    {
        public string Name { get; set; }
        public string Code { get; set; }
    }
}

SmartElectronicsApi.Mvc/Areas/AdminArea/Controllers/ColorController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SmartElectronicsApi.Mvc.ViewModels;
using SmartElectronicsApi.Mvc.ViewModels.Auth;
using SmartElectronicsApi.Mvc.ViewModels.Category;
using SmartElectronicsApi.Mvc.ViewModels.Color;
using SmartElectronicsApi.Mvc.ViewModels.pagination;
using System.Drawing.Printing;
using System.Net;
using System.Net.Http.Headers;
using System.Text;

namespace SmartElectronicsApi.Mvc.Areas.AdminArea.Controllers
{[Area("AdminArea")]
    public class ColorController : Controller
    {
        public async Task<IActionResult> Index(int pageNumber = 1, int pageSize = 2)
        {
            using var client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:5246/api/");
            client.DefaultRequestHeaders.Authorization =
      new AuthenticationHeaderValue("Bearer", Request.Cookies["JwtToken"]);
            using HttpResponseMessage httpResponseMessage = await client.GetAsync($"http://localhost:5246/api/Color?pageNumber={pageNumber}&pageSize={pageSize}");
            if (httpResponseMessage.IsSuccessStatusCode)
            {
                string ContentStream = await httpResponseMessage.Content.ReadAsStringAsync();
                var data = JsonConvert.DeserializeObject<PaginatedResponseVM<ColorListItemVM>>(ContentStream);
                return View(data);
            }
            else if (httpResponseMessage.StatusCode == HttpStatusCode.Unauthorized)
            {
                return RedirectToAction("Login", "Account", new { area = "" });
            }
            else if (httpResponseMessage.StatusCode == HttpStatusCode.Forbidden)
            {
                return RedirectToAction("AccessDenied", "Account", new { area = "" });
            }
            else
            {
                return RedirectToAction("Error404", "Home", new { area = "" });
            }
        }
        public IActionResult Create()
        {
            return View();  
        }
        [HttpPost]
        public async Task<IActionResult> Create(ColorVM colorVM)
        {
            using var client = new HttpClient();
            client.DefaultRequestHeaders.Authorization =
                  new AuthenticationHeaderValue("Bearer", Request.Cookies["JwtToken"]);
            var stringData = JsonConvert.SerializeObject(colorVM);
            var content = new StringContent(stringData, Encoding.UTF8, "application/json");
            using HttpResponseMessage httpResponseMessage = await client.PostAsync("http://localhost:5246/api/Color", content);
            if (httpResponseMessage.IsSuccessStatusCode)
            {

                TempData["CreatingSuccescolor"] = "Color  yaradildi";
                return RedirectToAction("Index");
            }
            else
            {
                var errorResponseString = await httpResponseMessage.Content.ReadAsStringAsync();
                var errorResponse = JsonConvert.DeserializeObject<ApiErrorResponse>(errorResponseString);
                if (errorResponse?.Errors != null)
                {
                    foreach (var error in errorResponse.Errors)
                    {
                        ModelState.AddModelError(error.Key, error.Value);
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, errorResponse?.Message ?? "An unknown error occurred.");
                }
                return View(colorVM);
            }
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            using var client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:5246/api/");
            var jwtToken = Request.Cookies["JwtToken"];
            if (string.IsNullOrEmpty(jwtToken))
            {
                return Json(new { success = false, message = "User not authenticated." });
            }
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", jwtToken);

            var response = await client.DeleteAsync($"http://localhost:5246/api/Color/{id}");
            if (response.IsSuccessStatusCode)
            {
                return Json(new { success = true, message = "Category successfully deleted." });
            }
            else
            {
                var errorResponseString = await response.Content.ReadAsStringAsync();
                var errorResponse = JsonConvert.DeserializeObject<ApiErrorResponse>(errorResponseString);

                if (errorResponse?.Errors != null && errorResponse?.Errors.Count() != 0)
                {
                    return Json(new { success = false, errors = errorResponse.Errors });
                }
                else
                {
                    return Json(new { success = false, message = errorResponse?.Message ?? "An unknown error occurred." });
                }
            }
        }
        public async Task<IActionResult> Update(int? id)
        {
            using var client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:5246/api/");
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", Request.Cookies["JwtToken"]);
            using HttpResponseMessage httpResponseMessage = await client.GetAsync($"http://localhost:5246/api/Color/{id}");
            if (httpResponseMessage.IsSuccessStatusCode)
            {
                string ContentStream = await httpResponseMessage.Content.ReadAsStringAsync();
                var data = JsonConvert.DeserializeObject<ColorVM>(ContentStream);
                return View(data);
            }
            else if (httpResponseMessage.StatusCode == HttpStatusCode.Unauthorized)
            {
                return RedirectToAction("Login", "Account", new { area = "" });
            }
            else if (httpResponseMessage.StatusCode == HttpStatusCode.Forbidden)
            {
                return RedirectToAction("AccessDenied", "Account", new { area = "" });
            }
            else
            {
                return RedirectToAction("Error404", "Home", new { area = "" });
            }
        }
        [HttpPost]
        public async Task<IActionResult> Update(int? id,ColorVM colorVM)
        {
            using var client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:5246/api/");
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", Request.Cookies["JwtToken"]);
            var stringData = JsonConvert.SerializeObject(colorVM);
            var content = new StringContent(stringData, Encoding.UTF8, "application/json");
            using HttpResponseMessage httpResponseMessage = await client.PutAsync($"http://localhost:5246/api/Color/{id}",content);
            if (httpResponseMessage.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            else
            {
                var errorResponseString = await httpResponseMessage.Content.ReadAsStringAsync();
                var errorResponse = JsonConvert.DeserializeObject<ApiErrorResponse>(errorResponseString);
                if (errorResponse?.Errors != null)
                {
                    foreach (var error in errorResponse.Errors)
                    {
                        ModelState.AddModelError(error.Key, error.Value);
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, errorResponse?.Message ?? "An unknown error occurred.");
                }
            }
            return View(colorVM);

        }
    }
}

SmartElectronicsApi.Mvc/Areas/AdminArea/Views/Color/Create.cshtml
@using SmartElectronicsApi.Mvc.ViewModels.Color
@model ColorVM
<row>
    <div class="col-md-6 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Horizontal Form</h4>
                <p class="card-description"> Color Create Page </p>
                <form asp-action="Create" method="post" class="forms-sample">
                    <div asp-validation-summary="All" class="text-danger"></div>

                    <div class="form-group row">
                        <label asp-for="Name" class="col-sm-3 col-form-label"></label>
                        <div class="col-sm-9">
                            <input asp-for="Name" class="form-control" placeholder="Name">
                            <span class="text-danger " asp-validation-for="Name"></span>
                        </div>
                        <label asp-for="Code" class="col-sm-3 col-form-label"></label>
                        <div class="col-sm-9">
                            <input asp-for="Code" type="color" class="form-control" placeholder="Code">
                            <span class="text-danger " asp-validation-for="Code"></span>
                        </div>
                    </div>

                    <button type="submit" class="btn btn-gradient-primary me-2">Submit</button>
                    <button class="btn btn-light">Cancel</button>
                </form>
            </div>
        </div>
    </div>
</row>

SmartElectronicsApi.Mvc/Areas/AdminArea/Views/Color/Index.cshtml
@using SmartElectronicsApi.Mvc.ViewModels.Color
@using SmartElectronicsApi.Mvc.ViewModels.pagination
@model PaginatedResponseVM<ColorListItemVM>
<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <div class="d-flex justify-content-between align-items-center">
                    <h4 class="card-title">Project Status</h4>
                    <!-- Create button -->
                    <a class="btn btn-primary btn-sm"  asp-action="Create" asp-controller="Color">Create New Color</a>
                </div>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th> # </th>
                                <th> Name </th>
                                <th> Settings </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Data)
                            {
                                <tr class="ColorTable" data-id="@item.Id">
                                    <td>@item.Id</td>
                                    <td>@item.Name</td>
                                    <td style="color:@item.Code" class="py-1">@item.Code</td>
                                    <td>
                                        <a class="btn btn-sm btn-primary" asp-action="Update" asp-controller="Color" asp-route-id="@item.Id">Edit</a>
                                        <button class="btn btn-sm btn-danger" onclick="DeleteColor(@item.Id) ">Delete</button>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        <li class="page-item @(Model.PageNumber == 1 ? "disabled" : "")">
            <a class="page-link" href="@Url.Action("Index", new { pageNumber = Model.PageNumber - 1, pageSize = Model.PageSize })" tabindex="-1">Previous</a>
        </li>

        @for (int i = 1; i <= Math.Ceiling((double)Model.TotalRecords / Model.PageSize); i++)
        {
            <li class="page-item @(i == Model.PageNumber ? "active" : "")">
                <a class="page-link" href="@Url.Action("Index", new { pageNumber = i, pageSize = Model.PageSize })">@i</a>
            </li>
        }

        <li class="page-item @(Model.PageNumber == Math.Ceiling((double)Model.TotalRecords / Model.PageSize) ? "disabled" : "")">
            <a class="page-link" href="@Url.Action("Index", new { pageNumber = Model.PageNumber + 1, pageSize = Model.PageSize })">Next</a>
        </li>
    </ul>
</nav>

@{
    if (TempData["CreatingSuccescolor"] != null)
    {
        <script>
            Swal.fire({
                icon: 'success',
                title: 'Created successfully',
                text: 'color created  successfully!',
                showConfirmButton: false,
                timer: 2000
            }).then(function () {
                window.location.href = '@Url.Action("Index", "Color")';
            });
        </script>
    }
}

SmartElectronicsApi.Mvc/Areas/AdminArea/Views/Color/Update.cshtml
@using SmartElectronicsApi.Mvc.ViewModels.Color
@model ColorVM
<row>
    <div class="col-md-6 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Horizontal Form</h4>
                <p class="card-description"> Color Create Page </p>
                <form asp-action="Update" method="post" class="forms-sample">
                    <div class="form-group row">
                        <label asp-for="Name" class="col-sm-3 col-form-label"></label>
                        <div class="col-sm-9">
                            <input asp-for="Name" class="form-control" placeholder="Name">
                            <span class="text-danger " asp-validation-for="Name"></span>
                        </div>
                        <label asp-for="Code" class="col-sm-3 col-form-label"></label>
                        <div class="col-sm-9">
                            <input asp-for="Code" type="color" class="form-control" placeholder="Code">
                            <span class="text-danger " asp-validation-for="Code"></span>
                        </div>
                    </div>

                    <button type="submit" class="btn btn-gradient-primary me-2">Submit</button>
                    <button class="btn btn-light" asp-action="Index">Cancel</button>
                </form>
            </div>
        </div>
    </div>
</row>