SmartElectronicsApi.Mvc/ViewModels/ParametrGroup/ParametrGroupCreateVM.cs
namespace SmartElectronicsApi.Mvc.ViewModels.ParametrGroup
{
    public class ParametrGroupCreateVM
    {
        public string Name { get; set; }
        public int ProductId { get; set; }
        public List<ParametrValueListItemVM> parametrValues { get; set; }
    }
}

SmartElectronicsApi.Mvc/ViewModels/ParametrGroup/ParametrGroupListItemVM.cs
namespace SmartElectronicsApi.Mvc.ViewModels.ParametrGroup
{
    public class ParametrGroupListItemVM
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<ParametrValueListItemVM> parametrValues { get; set; }
    }
}

SmartElectronicsApi.Mvc/ViewModels/ParametrGroup/ParametrValueListItemVM.cs
namespace SmartElectronicsApi.Mvc.ViewModels.ParametrGroup
{
    public class ParametrValueListItemVM
    {
        public string Type { get; set; }
        public string Value { get; set; }
    }
}

SmartElectronicsApi.Mvc/Areas/AdminArea/Controllers/ParametrGroupController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using SmartElectronicsApi.Mvc.ViewModels;
using SmartElectronicsApi.Mvc.ViewModels.Color;
using SmartElectronicsApi.Mvc.ViewModels.pagination;
using SmartElectronicsApi.Mvc.ViewModels.ParametrGroup;
using SmartElectronicsApi.Mvc.ViewModels.Product;
using SmartElectronicsApi.Mvc.ViewModels.ProductVariation;
using System.Net;
using System.Net.Http.Headers;
using System.Text;

namespace SmartElectronicsApi.Mvc.Areas.AdminArea.Controllers
{
    [Area("AdminArea")]
    public class ParametrGroupController : Controller
    {
        public async  Task<IActionResult> Index(int pageNumber = 1, int pageSize = 2)
        {
            using var client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:5246/api/");
            client.DefaultRequestHeaders.Authorization =
      new AuthenticationHeaderValue("Bearer", Request.Cookies["JwtToken"]);
            using HttpResponseMessage httpResponseMessage = await client.GetAsync($"http://localhost:5246/api/ParametrGroup?pageNumber={pageNumber}&pageSize={pageSize}");
            if (httpResponseMessage.IsSuccessStatusCode)
            {
                string ContentStream = await httpResponseMessage.Content.ReadAsStringAsync();
                var data = JsonConvert.DeserializeObject<PaginatedResponseVM<ParametrGroupListItemVM>>(ContentStream);
                return View(data);
            }
            else if (httpResponseMessage.StatusCode == HttpStatusCode.Unauthorized)
            {
                return RedirectToAction("Login", "Account", new { area = "" });
            }
            else if (httpResponseMessage.StatusCode == HttpStatusCode.Forbidden)
            {
                return RedirectToAction("AccessDenied", "Account", new { area = "" });
            }
            else
            {
                return RedirectToAction("Error404", "Home", new { area = "" });
            }
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int? id)
        {
            using var client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:5246/api/");
            var jwtToken = Request.Cookies["JwtToken"];
            if (string.IsNullOrEmpty(jwtToken))
            {
                return Json(new { success = false, message = "User not authenticated." });
            }
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", jwtToken);

            var response = await client.DeleteAsync($"http://localhost:5246/api/ParametrGroup/{id}");
            if (response.IsSuccessStatusCode)
            {
                return Json(new { success = true, message = "Category successfully deleted." });
            }
            else
            {
                var errorResponseString = await response.Content.ReadAsStringAsync();
                var errorResponse = JsonConvert.DeserializeObject<ApiErrorResponse>(errorResponseString);

                if (errorResponse?.Errors != null && errorResponse?.Errors.Count() != 0)
                {
                    return Json(new { success = false, errors = errorResponse.Errors });
                }
                else
                {
                    return Json(new { success = false, message = errorResponse?.Message ?? "An unknown error occurred." });
                }
            }
        }
        public async Task<IActionResult> Create()
        {
            using var client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:5246/api/");
            client.DefaultRequestHeaders.Authorization =
                  new AuthenticationHeaderValue("Bearer", Request.Cookies["JwtToken"]);
            using HttpResponseMessage productResponse = await client.GetAsync("http://localhost:5246/api/Product/GetAll");
            if (productResponse.IsSuccessStatusCode)
            {

                string contentStream = await productResponse.Content.ReadAsStringAsync();
                var products = JsonConvert.DeserializeObject<List<ProdutListItemVM>>(contentStream);
                ViewBag.products = new SelectList(products, "Id", "Name");
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(ParametrGroupCreateVM parametrGroupCreateVM)
        {
            using var client = new HttpClient();
            new AuthenticationHeaderValue("Bearer", Request.Cookies["JwtToken"]);
            if (!ModelState.IsValid)
            {
                await LoadViewBagData();
                return View(parametrGroupCreateVM);
            }
            var stringData = JsonConvert.SerializeObject(parametrGroupCreateVM);
            var content = new StringContent(stringData, Encoding.UTF8, "application/json");
            using HttpResponseMessage httpResponseMessage = await client.PostAsync("http://localhost:5246/api/ParametrGroup", content);
            if (httpResponseMessage.IsSuccessStatusCode)
            {

                return RedirectToAction("Index");

            }
            else
            {
                var errorResponseString = await httpResponseMessage.Content.ReadAsStringAsync();
                var errorResponse = JsonConvert.DeserializeObject<ApiErrorResponse>(errorResponseString);
                if (errorResponse?.Errors != null)
                {
                    foreach (var error in errorResponse.Errors)
                    {
                        ModelState.AddModelError(error.Key, error.Value);
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, errorResponse?.Message ?? "An unknown error occurred.");
                }
                await LoadViewBagData();
                return View(parametrGroupCreateVM);
            }
        }
        private async Task LoadViewBagData()
        {
            using var client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:5246/api/");
            client.DefaultRequestHeaders.Authorization =
                  new AuthenticationHeaderValue("Bearer", Request.Cookies["JwtToken"]);
           
            using HttpResponseMessage productResponse = await client.GetAsync("http://localhost:5246/api/Product/GetAll");
            if (productResponse.IsSuccessStatusCode)
            {

                string contentStream = await productResponse.Content.ReadAsStringAsync();
                var products = JsonConvert.DeserializeObject<List<ProdutListItemVM>>(contentStream);
                ViewBag.products = new SelectList(products, "Id", "Name");
            }
        }
    }
}

SmartElectronicsApi.Mvc/Areas/AdminArea/Views/ParametrGroup/Create.cshtml
@using SmartElectronicsApi.Mvc.ViewModels.ParametrGroup
@model ParametrGroupCreateVM

@{
    ViewData["Title"] = "Create Parametr";
}

<h2>Create Parametr</h2>

<form asp-action="Create" method="post">
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group row">
        <div class="col-sm-9">
            <select asp-for="ProductId" class="form-control">
                <option value="">Select ProductId</option>
                @foreach (var category in ViewBag.products)
                {
                    <option value="@category.Value">@category.Text</option>
                }
            </select>
            <span class="text-danger" asp-validation-for="ProductId"></span>
        </div>
    </div>

    <div class="form-group">
        <label>Parametr Values</label>
        <div id="parametrValuesContainer">
            <!-- Parametr Value Item -->
            <div class="parametrValueItem">
                <label>Type:</label>
                <input name="parametrValues[0].Type" class="form-control" />
                <label>Value:</label>
                <input name="parametrValues[0].Value" class="form-control" />
            </div>
        </div>
        <button type="button" onclick="addParametrValue()">Add Another Value</button>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>


    <script>
        let index = 1;
        function addParametrValue() {
            const container = document.getElementById("parametrValuesContainer");
            const newItem = document.createElement("div");
            newItem.classList.add("parametrValueItem");
            newItem.innerHTML = `
                        <label>Type:</label>
                                <input name="parametrValues[${index}].Type" class="form-control" />
                        <label>Value:</label>
                                <input name="parametrValues[${index}].Value" class="form-control" />
                    `;
            container.appendChild(newItem);
            index++;
        }
    </script>

SmartElectronicsApi.Mvc/Areas/AdminArea/Views/ParametrGroup/Index.cshtml
@using SmartElectronicsApi.Mvc.ViewModels.ParametrGroup
@using SmartElectronicsApi.Mvc.ViewModels.pagination
@model PaginatedResponseVM<ParametrGroupListItemVM>
<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <div class="d-flex justify-content-between align-items-center">
                    <h4 class="card-title">Project Status</h4>
                    <!-- Create button -->
                    <a class="btn btn-primary btn-sm" asp-action="Create" asp-controller="ParametrGroup">Create New Category</a>
                </div>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th> # </th>
                                <th> Name </th>
                             
                                <th> Settings </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Data)
                            {
                                <tr class="ParametrGroupTable" data-id="@item.Id">
                                    <td>@item.Id</td>
                                   
                                    <td>@item.Name</td>
                                    
                                    <td>
                                        <a class="btn btn-sm btn-primary" asp-action="Update" asp-controller="Category" asp-route-id="@item.Id">Edit</a>
                                        <button class="btn btn-sm btn-danger" onclick="DeleteParametrGroupTable(@item.Id) ">Delete</button>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>









<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        <li class="page-item @(Model.PageNumber == 1 ? "disabled" : "")">
            <a class="page-link" href="@Url.Action("Index", new { pageNumber = Model.PageNumber - 1, pageSize = Model.PageSize })" tabindex="-1">Previous</a>
        </li>

        @for (int i = 1; i <= Math.Ceiling((double)Model.TotalRecords / Model.PageSize); i++)
        {
            <li class="page-item @(i == Model.PageNumber ? "active" : "")">
                <a class="page-link" href="@Url.Action("Index", new { pageNumber = i, pageSize = Model.PageSize })">@i</a>
            </li>
        }

        <li class="page-item @(Model.PageNumber == Math.Ceiling((double)Model.TotalRecords / Model.PageSize) ? "disabled" : "")">
            <a class="page-link" href="@Url.Action("Index", new { pageNumber = Model.PageNumber + 1, pageSize = Model.PageSize })">Next</a>
        </li>
    </ul>
</nav>